/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasicatatanharian;

import java.net.URL;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author ACER
 */
public class DialogBuatCatatan extends javax.swing.JDialog {

    private String getWeather(String cityName, String apiKey) {
        try {
            // Membuat URL untuk API
            String urlString = "http://api.openweathermap.org/data/2.5/weather?q=" + cityName + "&appid=" + apiKey + "&units=metric";
            URL url = new URL(urlString);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("GET");

            // Membaca respons dari API
            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            StringBuilder response = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                response.append(line);
            }
            reader.close();

            // Parsing JSON untuk mendapatkan cuaca
            JSONObject jsonResponse = new JSONObject(response.toString());
            double temp = jsonResponse.getJSONObject("main").getDouble("temp");
            String weather = jsonResponse.getJSONArray("weather").getJSONObject(0).getString("description");

            return "Cuaca: " + weather + ", Suhu: " + temp + "°C";
        } catch (Exception e) {
            e.printStackTrace();
            return "Gagal mengambil cuaca.";
        }
    }

    private Catatan catatan; // Catatan yang sedang diedit
    private CatatanDatabaseHelper dbHelper;

    /**
     * Creates new form DialogBuatCatatan
     */
    public DialogBuatCatatan(java.awt.Frame parent, boolean modal, CatatanDatabaseHelper dbHelper) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent); // Pindah dialog ke tengah parent

        this.dbHelper = dbHelper;
    }

    public void setCatatan(Catatan catatan) {
        this.catatan = catatan;
        if (catatan != null) {
            txtJudul.setText(catatan.getJudul());
            txtCuaca.setText(catatan.getCuaca());
            txtIsiCatatan.setText(catatan.getIsiCatatan());
            datePilih.setDate(catatan.getTanggal());
        } else {
            // Jika null, kosongkan form untuk tambah catatan baru
            txtJudul.setText("");
            txtCuaca.setText("");
            txtIsiCatatan.setText("");
            datePilih.setDate(null);
        }
    }

    public Catatan updateCatatan() {
        if (catatan == null) {
            catatan = new Catatan(); // Buat catatan baru jika tidak ada
        }
        catatan.setJudul(txtJudul.getText());
        catatan.setCuaca(txtCuaca.getText());
        catatan.setIsiCatatan(txtIsiCatatan.getText());
        catatan.setTanggal(datePilih.getDate());
        return catatan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        txtJudul = new javax.swing.JTextField();
        txtCuaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIsiCatatan = new javax.swing.JTextArea();
        datePilih = new com.github.lgooddatepicker.components.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCek = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtJudul, gridBagConstraints);

        txtCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuacaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtCuaca, gridBagConstraints);

        txtIsiCatatan.setColumns(20);
        txtIsiCatatan.setRows(5);
        jScrollPane1.setViewportView(txtIsiCatatan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(datePilih, gridBagConstraints);

        jLabel1.setText("Judul");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Tanggal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Cuaca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Isi Catatan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jLabel4, gridBagConstraints);

        btnCek.setText("Cek Cuaca");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(btnCek, gridBagConstraints);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuacaActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (txtJudul.getText().isEmpty() || datePilih.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Judul dan tanggal harus diisi!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        updateCatatan();  // Mengambil data catatan dari form
        if (catatan.getId() == -1) { // Jika ID -1, berarti catatan baru
            dbHelper.tambahCatatan(catatan); // Simpan catatan baru
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Catatan berhasil disimpan!",
                    "Sukses",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else { // Jika ID sudah ada, lakukan update
            dbHelper.updateCatatan(catatan);
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Catatan berhasil diperbarui!",
                    "Sukses",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

        this.dispose(); // Tutup dialog setelah simpan/update
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose(); // Langsung tutup dialog
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
      // Menampilkan dialog untuk memilih kota
    String cityName = JOptionPane.showInputDialog(this, "Masukkan nama kota:", "Pilih Kota", JOptionPane.QUESTION_MESSAGE);
    
    if (cityName != null && !cityName.isEmpty()) {
        // Jika kota dipilih, ambil cuaca
        String apiKey = "e57367f6bf9f06154278b83d65a4a557";  // Ganti dengan API Key Anda
        String weather = getWeather(cityName, apiKey);
        txtCuaca.setText(weather);
    } else {
        // Jika nama kota kosong atau dibatalkan, tampilkan pesan
        JOptionPane.showMessageDialog(this, "Kota tidak dipilih. Cuaca tidak dapat ditampilkan.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnCekActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnSimpan;
    private com.github.lgooddatepicker.components.DatePicker datePilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCuaca;
    private javax.swing.JTextArea txtIsiCatatan;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
